export { default as logo } from "../assets/img/Logo.svg";
export { default as eyeOpen } from "../assets/img/eye-open.svg";
export { default as eyeSlash } from "../assets/img/eye-slash.svg";
export { default as lock } from "../assets/img/lock.svg";
export { default as user } from "../assets/img/user.svg";
export { default as arrow } from "../assets/img/arrow-left.svg";
export { default as success } from "../assets/img/success.svg";
export { default as bar } from "../assets/img/bar.svg";
export { default as search } from "../assets/img/search.svg";
export { default as bell} from "../assets/img/notification.svg";
export { default as burger} from "../assets/img/menu.svg";
export { default as close} from "../assets/img/close.svg";
export { default as arrowRight} from "../assets/img/arrow-right.svg";
export { default as calendar} from "../assets/img/calendar.svg";
export { default as alert} from "../assets/img/info-circle.svg";
export { default as master_card} from "../assets/img/master_card.svg";
export { default as eye} from "../assets/img/eye.svg";
export { default as card_receive} from "../assets/img/card-receive.svg";
export { default as card_send} from "../assets/img/card-send.svg";
export { default as arrow_card2} from "../assets/img/arrow_card2.svg";
export { default as car} from "../assets/img/car.jpg";
export { default as console} from "../assets/img/console.jpg";
export { default as money} from "../assets/img/money.jpg";
export { default as girl} from "../assets/img/girl.png";
export { default as arrow_down} from "../assets/img/arrow-down.svg";
export { default as diagram} from "../assets/img/Statistics.svg";
export { default as bargraph} from "../assets/img/bargraph.svg";
export { default as linegraph} from "../assets/img/linegraph.svg";
export { default as figma} from "../assets/img/figma.svg";
export { default as fi} from "../assets/img/fi.svg";
export { default as cloud} from "../assets/img/cloud.svg";
export { default as starbucks} from "../assets/img/starbucks.svg";
export { default as Rupiah} from "../assets/img/Rupiah.svg";
export { default as Euro} from "../assets/img/Euro.svg";
export { default as China} from "../assets/img/china.svg";